key_info = {
    "RECAM": '''
        **RECAM Key Information**
            - drug_name (str): name of the drug (generic name).
            - onset_after_start (int): number of days between hepatotoxicity onset and start of drug exposure. Only extract the number of days from the input data. Do not include units in the output.
            - onset_after_stop (int): number of days between hepatotoxicity onset and stop of drug exposure. Only extract the number of days from the input data. Do not include units in the output. If not found, set to None.
            - long_half_life (bool): whether the drug has a long half life.
            - sex (str): Sex, either "male" or "female". Only extract the sex information from the input data.
            - ast (float): AST (Aspartate Aminotransferase) reading at the time of injury onset, in U/L. Only extract the AST reading from the input data. Convert the unit to U/L if needed. Do not include units in the output.
            - alt (float): ALT (Alanine Aminotransferase) reading at the time of injury onset, in U/L. Only extract the ALT reading from the input data. Convert the unit to U/L if needed. Do not include units in the output.
            - alp (float): ALP (Alkaline Phosphatase) reading at the time of injury onset, in U/L. Only extract the ALP reading from the input data. Convert the unit to U/L if needed. Do not include units in the output.
            - bili (float): Bilirubin reading at the time of injury onset, in mg/dL. Only extract the Bilirubin reading from the input data. Convert the unit to mg/dL if needed. Do not include units in the output.
            - alt_baseline (float): ALT (Alanine Aminotransferase) reading at baseline (before drug exposure), in U/L. Only extract the ALT reading from the input data. Convert the unit to U/L if needed. Do not include units in the output. If not found in the input data, set to None.
            - alp_baseline (float): ALP (Alkaline Phosphatase) reading at baseline (before drug exposure), in U/L. Only extract the ALP reading from the input data. Convert the unit to U/L if needed. Do not include units in the output. If not found in the input data, set to None.
            - bili_baseline (float): Bilirubin reading at baseline (before drug exposure), in mg/dL. Only extract the Bilirubin reading from the input data. Convert the unit to mg/dL if needed. Do not include units in the output. If not found in the input data, set to None.
            - alt_elevation (float): ALT elevation, in how many times of ALT ULN or the baseline. Convert the unit to x times of ULN if needed. Do not include units in the output. If not found in the input data, set to None.
            - alp_elevation (float): ALP elevation, in how many times of ALP ULN or the baseline. Convert the unit to x times of ULN if needed. Do not include units in the output. If not found in the input data, set to None.
            - bili_elevation (float): Bilirubin elevation, in how many times of Bilirubin ULN or the baseline. Convert the unit to x times of ULN if needed. Do not include units in the output. If not found in the input data, set to None.
            - days_to_50pct_alt_decline (float): number of days to 50% decline in ALT elevation (compared to the peak ALT elevation). Only extract the number of days from the input data. Do not include units in the output.
            - drug_taken_at_50pct_alt_decline (bool): whether the drug is still taken at 50% decline in ALT elevation.
            - alt_declined_below_50pct (bool): whether the ALT has declined below 50% of the peak ALT elevation.
            - days_to_50pct_alp_decline (float): number of days to 50% decline in ALP elevation (compared to the peak ALP elevation).
            - drug_taken_at_50pct_alp_decline (bool): whether the drug is still taken at 50% decline in ALP elevation.
            - alp_declined_below_50pct (bool): whether the ALP has declined below 50% of the peak ALP elevation.
            - days_to_50pct_bili_decline (float): number of days to 50% decline in Bilirubin elevation as compared to the peak Bilirubin elevation.
            - drug_taken_at_50pct_bili_decline (bool): whether the drug is still taken at 50% decline in Bilirubin.
            - bili_declined_below_50pct (bool): whether the Bilirubin has declined below 50% at 50% decline in Bilirubin.
            - persistent_high (bool): whether the ALT, ALP or Bilirubin (whichever used by R-value criteria above) is > 90% of peak value at anytime >182 days and prior to any transplant without other explanation recurrent or persistent elevation.
            - livertox_category (str): LiverTox category, either "A", "B", "C", "D", "E", or "X".
            - missing_IgM_anti_HAV (bool): whether IgM anti-HAV data is missing. HAV stands for Hepatitis A virus.
            - IgM_anti_HAV (bool): whether IgM anti-HAV is positive (if total anti-HAV is negative, consider IgM negative as well). HAV stands for Hepatitis A virus.
            - missing_IgM_anti_HBc (bool): whether IgM anti-HBc data is missing. HBc stands for Hepatitis B core antigen. Note: (−) anti-HBc total means IgM is negative, but (+) anti-HBc total does not inform IgM result.
            - HBsAg (bool): whether HBsAg is positive. HBsAg stands for Hepatitis B surface antigen. 
            - IgM_anti_HBc (bool): whether IgM anti-HBc is positive. HBc stands for Hepatitis B core antigen. If total anti-HBc is negative, consider IgM negative; anti-HBc igG may be + or −.
            - missing_anti_HCV (bool): whether anti-HCV data is missing. HCV stands for Hepatitis C virus.
            - missing_HCV_RNA (bool): whether HCV RNA data is missing. HCV stands for Hepatitis C virus.
            - anti_HCV (bool): whether anti-HCV is positive. HCV stands for Hepatitis C virus.
            - HCV_RNA (bool): whether HCV RNA is positive. HCV stands for Hepatitis C virus.
            - chronic_HCV (bool): whether known chronic infection of HCV is present. HCV stands for Hepatitis C virus.
            - HCV_risk_100d_before_onset (bool): whether exposure risk is present less than 100 days before the onset of hepatotoxicity. HCV stands for Hepatitis C virus.
            - missing_IgM_anti_HEV (bool): whether IgM anti-HEV data is missing. HEV stands for Hepatitis E virus.
            - IgM_anti_HEV (bool): whether IgM anti-HEV is positive. HEV stands for Hepatitis E virus.
            - standard_drinks_per_day (int): number of standard drinks per day within 6 weeks of injury onset. A standard drink in the U.S. contains 0.6 fluid ounces (14 grams) of pure alcohol. For example, a standard drink is equivalent to about 12 ounces of beer, 5 ounces of wine, or 1.5 ounces of 80-proof distilled spirits. If not found, set to 0.
            - missing_image_biliary_or_parenchymal_disease (bool): whether imaging data for biliary or parenchymal disease is missing. Imaging data includes ultrasound (US), computed tomography scan (CT), magnetic resonance imaging (MRI), magnetic resonance cholangiopancreatography (MRCP), cholangiogram, etc.
            - biliary_steuosis_or_obstruction (bool): whether imaging data shows biliary steuosis(es) or obstruction. Imaging data includes ultrasound (US), computed tomography scan (CT), magnetic resonance imaging (MRI), magnetic resonance cholangiopancreatography (MRCP), cholangiogram, etc.
            - less_than_50pct_malignant_infiltration (bool): whether imaging data shows infiltrating malignancy occupying ≥ 50% of the liver. Imaging data includes ultrasound (US), computed tomography scan (CT), magnetic resonance imaging (MRI), magnetic resonance cholangiopancreatography (MRCP), cholangiogram, etc.
            - is_minocycline_or_nitrofurantion_case (bool): whether the drug belongs to minocycline or nitrofurantion family. If needed, search the drug name in the internet to determine if it belongs to this family.
            - ANA_autoimmune_hepatitis (float): ANA (antinuclear antibodies) reading at the time of injury onset, in ratio. For example, if the ANA reading is 1:80, set to a float value of 1/80.
            - ASMA_autoimmune_hepatitis (float): ASMA (anti-smooth muscle antibodies) reading at the time of injury onset, in ratio. For example, if the ASMA reading is 1:80, set to a float value of 1/80.
            - IgG_autoimmune_hepatitis (float): IgG reading suggesting autoimmune hepatitis at the time of injury onset, in U/L.
            - missing_ischemic_liver_injury_data (bool): whether ischemic liver injury data is missing. If no information is found for possible hypoxia, hypotension, shock or acute congestive hepatopathy (history incomplete or inadequate), set to True.
            - ischemic_liver_injury_1w_before_onset (bool): whether ischemic liver injury (possible hypoxia, hypotension, shock or acute congestive hepatopathy) is present 1 week before the onset of hepatotoxicity.
            - missing_sepsis (bool): whether sepsis data is missing. If no information is found for sepsis or SIRS (systemic inflammatory response syndrome), set to True.
            - sepsis (bool): whether sepsis or SIRS (systemic inflammatory response syndrome) is present.
            - prior_exposure_dili_jaundice (bool): whether the patient has a history of prior exposure to the drug and found to have DILI with jaundice after that prior exposure to the drug. Documentation by lab results is not necessary.
            - rechallenge_data (bool): whether rechallenge data is available and the rechallenge data is documented with lab results (e.g., AST, ALT, ALP).
            - rechallenge_ast_alt_elevation (bool): whether rechallenge of the drug resulted in AST or ALT elevation more than 3x ULN (or baseline) within 90 Days after the rechallenge.
            - rechallenge_alp_elevation (bool): whether rechallenge of the drug resulted in ALP elevation more than 2x ULN (or baseline) within 90 Days after the rechallenge.
            - rechallenge_no_ast_alt_elevation (bool): whether rechallenge of the drug showed non-significant AST or ALT elevation (less than 2x ULN or baseline).
            - rechallenge_no_alp_elevation (bool): whether rechallenge of the drug showed non-significant ALP elevation (less than 2x ULN or baseline).
            - liver_biopsy_specific_dili (bool): whether liver biopsy data shows features consistent with a specific DILI.
            - liver_biopsy_non_dili (bool): whether liver biopsy data suggests non-DILI diagnosis (e.g. infiltrating cancer, ischemic injury, alcoholic hepatitis).
            - missing_IgM_anti_CMV (bool): whether IgM anti-CMV data is missing. CMV stands for Cytomegalovirus.
            - IgM_anti_CMV (bool): whether IgM anti-CMV is positive. CMV stands for Cytomegalovirus.
            - CMV_DNA (bool): whether CMV DNA is detected by PCR. CMV stands for Cytomegalovirus.
            - missing_IgM_anti_EBV (bool): whether IgM anti-EBV data is missing. EBV stands for Epstein-Barr virus.
            - IgM_anti_EBV (bool): whether IgM anti-EBV is positive. EBV stands for Epstein-Barr virus.
            - EBV_DNA (bool): whether EBV DNA is detected by PCR. EBV stands for Epstein-Barr virus.
            - missing_IgM_anti_HSV (bool): whether IgM anti-HSV data is missing. HSV stands for Herpes simplex virus.
            - IgM_anti_HSV (bool): whether IgM anti-HSV is positive. HSV stands for Herpes simplex virus.
            - HSV_DNA (bool): whether HSV DNA is detected by PCR. HSV stands for Herpes simplex virus.
            - DRESS_or_SJS (bool): whether Drug Reaction with Eosinophila and Systemic Symptoms (DRESS) or Steven Johnsons Syndrome (SJS) is present.
        ''',
}
